### ISSUE TITLE
After close app all data are erase 

### ISSUE THREAD

**Issue by NetPumi2** [ammarahm-ed/react-native-mmkv-storage#156]
Hello, we have a problem with persisting our project data after the iOS app is completely closed. After (or before) re-opening app data are erased and we can not get them ...Android works fine... 

this is our implementation of this storage 

```
...
import MMKVStorage from 'react-native-mmkv-storage';

const MMKVwithEncryption = new MMKVStorage.Loader().withEncryption().initialize();

export const setItem = async (key: string, value: string): Promise<void> => {
  try {
    await MMKVwithEncryption.setStringAsync(key, value);
  } catch (error) {
    analytics().logEvent('mmkv_storage', {
      operation: 'set_string_async',
      message: `Failed to get item. Error: ${error}`,
    });
  }
};

export const getItem = async (key: string): Promise<string | null | undefined> => {
  try {
    return await MMKVwithEncryption.getStringAsync(key);
  } catch (error) {
    analytics().logEvent('mmkv_storage', {
      operation: 'get_string_async',
      message: `Failed to get item. Error: ${error}`,
    });
  }
};
...
```

I checked the example app in this project and it works fine. We just dont create(store) but we are using keys. What could be wrong? Some ios implementation? Because android works fine in this case...

**UPDATE**

usage example:
AppContext.tsx we are loading raw data to our context storage:
```
  const loadData = async () => {
    ...
    const paringRawData = await TEMP_readFromAvailableStorage(PAIRING_PROCESS);
....
}
```

And this  function is how we get data from storage we just call getItem(key) (rest is because we migrate from old storage to this storage... you can ignore it ...)
```
export const TEMP_readFromAvailableStorage = async (key: string): Promise<string | null | undefined> => {
  const hasMigrated = await MMKVwithEncryption.getBoolAsync(HAS_MIGRATED_FROM_ASYNC_STORAGE);
  // console.log('DELETE TEMP_readFromAvailableStorage hasMigrated:', hasMigrated);

  if (!hasMigrated) {
    return await DEPRECATED_getData(key);
  }

  return await getItem(key);
};
```

this is how we put data to MMKW  ( setItem() ) it is a function in the context:
```
  const onSetPairingData = (data?: PairingDataType) => {
    const updatedPairingData = { ...pairingData, ...data };

    setItem(PAIRING_PROCESS, JSON.stringify(updatedPairingData));
    setPairingData(updatedPairingData);
  };
```

**Platform Information:**
 - OS: IOS
 - React Native Version 0.64.1
 - Library Version ^0.6.0"

**Comment by ammarahm-ed** [comment]
@NetPumi2 Put your get/set methods in the example app and test again. Also the setItem and getItem methods are exposed by the library, you do not need to recreate them.

**Comment by ammarahm-ed** [comment]
@NetPumi2  Also try adding library like this to use the unreleased version in your project and try again.

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```

**Comment by NetPumi2** [comment]
Ok, ill try ill be back in 1h (I have a meeting) thank you for helping us ...

**Comment by NetPumi2** [comment]
@ammarahm-ed  no it doesn't work ... :(

**Comment by ammarahm-ed** [comment]
@NetPumi2 Does it work in the example?

**Comment by NetPumi2** [comment]
yes
example works fine

**Comment by ammarahm-ed** [comment]
Well then the issue is in your app. The library stores its database file in app storage on iPhone. Is there by any chance a library that you are using which clears that directory? Also have you tried to initialise without encryption and test.

**Comment by NetPumi2** [comment]
ill check if that file is there but we don't use anything to manage file/folders in app ....  ill try init it without encryption  and let you know

**Comment by ammarahm-ed** [comment]
I have tested again and it's working normally even with encryption. Also try to clear Pods folder in /ios directory and delete node_modules and install library again. Run pod install and run your app.

**Comment by NetPumi2** [comment]
@ammarahm-ed  It is working without `.withEncryption()` -> but we switch to this lib because we need to encrypt our data ... I tried some dummy storage with a new instance of MMKV and with encryption and it also doesn't work .... (I erase pods and node_modules and also the project is setup for ios 11 and emulate what I am using is 14.x (real test device have latest update ))

**Comment by ammarahm-ed** [comment]
@NetPumi2 Are you giving your own password when encrypting using `withEncryption()` or using the one generated by library internally? 

The example app also uses encryption by default as you might have seen and it works. Today I tested in ios simulator 14.x and it was working. Does it work in simulator for you?

**Comment by NetPumi2** [comment]
I am using the default password ... I am pretty sure there is some issue in our implementation. We have got file name store.ts and inside this file, we exported all of our impl and MMKV is a global variable it is not in but we don't use it in a component can it be a problem? ... because when I init library and using it in component it works fine ...

**Comment by bolyesz** [comment]
Hi, I'm working on this problem together with @NetPumi2. Today we found out that there's probably a problem with the initialisation of the storage on iOS, android is working fine... So we used these two methods: `getAllMMKVInstanceIDs` and `getCurrentMMKVInstances` to log out the instances, and we compared our results on iOS and android. On android the instance of the storage is present and it's also **initialised**...but on iOS the instance of the storage is only initialised on the first run of the app, and then it doesn't get initialised anymore (**initialised: false**). We think that the problem lies there, because if the storage is not initialised we cannot read from it, which is also proved by the result of setting an item into the storage, on android it's `true` but on iOS the result is `undefined`. 

Do you have an idea what might be the problem that the storage gets initialised on android but not on iOS? We checked also the configs in the example app and compared it to ours, but we didn't find anything so far...

**Comment by ammarahm-ed** [comment]
@bolyesz @NetPumi2  The problem seems to be obvious now. JSI Bindings are not getting installed on iOS in your project which is causing this problem. Try this confirm after restarting the app on iOS
```js
console.log(global.getStringMMKV) // It should log [Function xx] on iOS and Android both. 
```
If it logs `[Function...` even after restarting then the problem lies in decrypting storage instance. Can you share your package.json file? I want to see what other libraries you have installed.

Also if you can share a bare minimum project that can reproduce the issue. I will try to see what is happening. You can remove your javascript private code from your project but keep all the libraries etc intact with a simple App.js file that initializes the library and does some read/write operation for testing. Share it with me and I will try to debug this.

I am sure the problem is within your project but I can't track it without having something.

**Comment by msvargas** [comment]
I have the same problem :) thank yo

**Comment by msvargas** [comment]
I have the same issue, the console.log is correct @ammarahm-ed 

Thank you

![image](https://user-images.githubusercontent.com/8255332/132905047-132e5d76-26ff-4f65-9b36-fc8c3fcf1611.png)

**Comment by ammarahm-ed** [comment]
> the console.log is correct @ammarahm-ed 
> ![image](https://user-images.githubusercontent.com/8255332/132905047-132e5d76-26ff-4f65-9b36-fc8c3fcf1611.png)
> 

What other libraries do you have installed? Anything related to keychain/keystore?

Also does the library work normally for you without encryption?

**Comment by ammarahm-ed** [comment]
> I have the same issue, the console.log is correct @ammarahm-ed 
> 
> Thank you
> 
> ![image](https://user-images.githubusercontent.com/8255332/132905047-132e5d76-26ff-4f65-9b36-fc8c3fcf1611.png)
> 

It will be really helpful if you can provide a minimum reproducible example. Right now I am unable to reproduce this on ios simulator 14.x.

**Comment by msvargas** [comment]
> > the console.log is correct @ammarahm-ed
> > ![image](https://user-images.githubusercontent.com/8255332/132905047-132e5d76-26ff-4f65-9b36-fc8c3fcf1611.png)
> 
> What other libraries do you have installed? Anything related to keychain/keystore?
> 
> Also does the library work normally for you without encryption?

Yes, I use in my project react-native-keychain and yes, without encryption the library works normally

**Comment by msvargas** [comment]
> > I have the same issue, the console.log is correct @ammarahm-ed
> > Thank you
> > ![image](https://user-images.githubusercontent.com/8255332/132905047-132e5d76-26ff-4f65-9b36-fc8c3fcf1611.png)
> 
> It will be really helpful if you can provide a minimum reproducible example. Right now I am unable to reproduce this on ios simulator 14.x.

Of course, thanks for your quick response

**Comment by ammarahm-ed** [comment]
> > > I have the same issue, the console.log is correct @ammarahm-ed
> > > Thank you
> > > ![image](https://user-images.githubusercontent.com/8255332/132905047-132e5d76-26ff-4f65-9b36-fc8c3fcf1611.png)
> > 
> > It will be really helpful if you can provide a minimum reproducible example. Right now I am unable to reproduce this on ios simulator 14.x.
> 
> Of course, thanks for your quick response

Can you try removing the react-native-keychain lib temporarily and testing mmkv again or init a new project with both libraries installed and test.

**Comment by msvargas** [comment]
@ammarahm-ed  without react-native-keychain your library working fine :), but I need biometric authentication :(

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed  without react-native-keychain your library working fine :), but I need biometric authentication :( 

I will try to debug this tomorrow and see what might be causing the problem.

**Comment by msvargas** [comment]
@ammarahm-ed Thanks

**Comment by ammarahm-ed** [comment]
@msvargas What version of react-native-keychain are you using in your porject?

**Comment by ammarahm-ed** [comment]
@msvargas  Are you using `setGenericPassword` method in `react-native-keychain` to store credentials?

The issue seems to be that `react-native-keychain` removes all values from the default service whenever you write a new value. This results in removal of credentials store by my library. 

This can be easily fixed by using any of the below:

**A. Use `setGenericPassword` with a custom service name**
 ```js
await Keychain.setGenericPassword(username ,password,{
          service:'myappservice',
          ... //remaining options
        })
```

**B. Use `setInternetCredentials`**

```js
 await Keychain.setInternetCredentials(server,username,password,{
          ...options
        })
```

Let me know if making this change fixes your issue.

Same for @bolyesz and @NetPumi2

**Comment by msvargas** [comment]
@ammarahm-ed Can I replace react-native-keychain with your library? Do they have the same level of security? thanks

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed Can I replace react-native-keychain with your library? Do they have the same level of security? thanks

They have however you cannot use biometrics etc with my library. It is just for internal use by the library components and the api is not exposed. 


But again, you don't need to replace. The above solution will work perfectly. All you need to do is provide service name as I did above and you are good to go.

**Comment by jaltin** [comment]
Hi @ammarahm-ed . You wrote the following:

>The issue seems to be that react-native-keychain removes all values from the default service whenever you write a new value. This results in removal of credentials store by my library.

> This can be easily fixed by using any of the below:
> 
> **A. Use `setGenericPassword` with a custom service name**
> 
> ```js
> await Keychain.setGenericPassword(username ,password,{
>          service:'myappservice',
>          ... //remaining options
>        })
> ```

It seems that we have stumbled on this problem too. The problem for us is that we are not using 'react-native-keychain' library but that other libraries that we have in our app is using keychain natively and are modifying the default store. This makes it hard for us to fix with a custom service name as you suggested.

Is it possible for this library to define a custom service name when persisting the the credentials and solve it that way, or is there perhaps another solution you can think of ?

Many thanks!

**Comment by ammarahm-ed** [comment]
@jaltin The best solution for you would be that you don't clear the default keystore when whenever you write a new value since the default keystore can hold multiple values and clear individual values if needed. 

I can't change how this library is working since it will cause a breaking change for anyone using encrypted storage. 

The other option is that you fork the master branch and use a different service name for your project. 

Changing the service name is a pretty simple process. By default the library uses app bundle id as service name. You can use something different and the store will persist.

https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/63346b27fd4e006dec7ea0dabec7f5903022273a/ios/SecureStorage.m#L97

From:
```objc
- (NSMutableDictionary *)newSearchDictionary:(NSString *)identifier {
    NSMutableDictionary *searchDictionary = [[NSMutableDictionary alloc] init];
    serviceName = [[NSBundle mainBundle] bundleIdentifier];
```
To: 
```objc
- (NSMutableDictionary *)newSearchDictionary:(NSString *)identifier {
    NSMutableDictionary *searchDictionary = [[NSMutableDictionary alloc] init];
  serviceName = @"myservice.name"
```

You can do something similar in your own native code for keychain too. 


EDIT:
Now that I am thinking, it might be possible to use a custom service name if needed. I will add it in the next version.

**Comment by jaltin** [comment]
@ammarahm-ed thanks a lot for your quick and extensive response.

The problem for us is that we are not writing to keychain. Other 3rd party npm packages we use (e.g. Realm, bugsnag and others) are writing to Keychain and we suspect that one of them updating keychain values causes us to loose all our encrypted data that we have stored with this library.

If you can fix this by allowing a custom service name, then that would be great.

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed thanks a lot for your quick and extensive response.
> 
> The problem for us is that we are not writing to keychain. Other 3rd party npm packages we use (e.g. Realm, bugsnag and others) are writing to Keychain and we suspect that one of them updating keychain values causes us to loose all our encrypted data that we have stored with this library.
> 
> If you can fix this by allowing a custom service name, then that would be great.

I will add this in the next release. Until then you can fork this repo and make the above change as I mentioned and test if it works as expected.

**Comment by jaltin** [comment]
Thanks! My colleague @andrei-tofan will have a go at making the changes that you propose.

We will post back with an update on how it went and possibly a PR if it works well.

**Comment by jaltin** [comment]
@ammarahm-ed As you might have seen, there is now a pull request to support serviceName. Can you have a look at it and let us know your thoughts? Thx!
