### ISSUE TITLE
[Question] Android java usage or big file import

### ISSUE THREAD

**Issue by HugoGresse** [ammarahm-ed/react-native-mmkv-storage#162]
Hi there,

First, good job on putting this together. Some library are quick to do, this one is totaly not small and easy to do! 

I need to import rather large data (around 50k keys) into MMKV to be read later one. So using a key/value storage is perfect for me (the total data size in .json is around 20MB). 

Is there a way to populate the mmkv at once providing a big Map<key:string, string> with such big quantity of data? 
If not, could we use the same already initialized mmkv instance from my own RNModule to remove the rn->js communication overhead? 

Writing 1k strings takes already 17s..., so 33k set will take around 10min...

**Comment by ammarahm-ed** [comment]
What version of the library are you using?

**Comment by HugoGresse** [comment]
v `0.6.0`

**Comment by ammarahm-ed** [comment]
First thing to understand is that there is no RN to JS overhead in this library. It's direct JS to C++ communication through JSI.

If you do the same thing in Java, there again will be an overhead of accessing C++ from Java through JNI because ultimately the mmkv library is written in C++. 

You are saying that writing 1000 keys at once takes 17s. Does this also include reading 1000 keys and parsing your 20 mb JSON data?

**Comment by HugoGresse** [comment]
Reading a 33k lines file takes around 3-10seconds. 
200 ms to JSON.parse() it

Then iterating on it to setString(). 

I did not test the read part as this prior steps taking so long is a blocker for me anyway. 
I agree there is an additional JSON.stringify done but I've tested writing a fixed string like "aaa" and it doesn't go much faster
 
Something like this: 
```

    console.time("read " + filePath);
    const data = await readFile(filePath)
    console.timeEnd("read " + filePath);

    console.time("parse " + filePath);
    const dataJson = JSON.parse(data)
    console.timeEnd("parse " + filePath);

    console.time("write " + filePath);
    for(let i = 0; i < dataJson.length; i++) {
        console.log(i);
         storage.setString(prefix+i, JSON.stringify(dataJson[i]))
    }
    console.timeEnd("write " + filePath);
    ```
    
    I also use the encryption of the db

**Comment by ammarahm-ed** [comment]
So once you have read the data and parsed it from JSON. Iterating over it and writing to storage itself is taking 17s for 1000 keys, am I right?

Encryption does not slow down read/write.

**Comment by HugoGresse** [comment]
Yes you're right, 17s on an emulator, around 7s on a real mid range device.

**Comment by ammarahm-ed** [comment]
Have you tried doing the same with `react-native-async-storage` and seeing how much time that takes, more or less for the same data? 

Also how much time does it take in release build? You can use `global.performance.now()` for release mode.

**Comment by HugoGresse** [comment]
I have some issues with the release build. Do you have some approximate numbers regarding performance in release? 
Like 2 times the perf? 

I don't want to waste my time using AsyncStorage though 😅

**Comment by ammarahm-ed** [comment]
@HugoGresse I tested in release. it's the same as debug, no difference. I am testing I will share some details in a bit

**Comment by HugoGresse** [comment]
In the meantime, I think I will stick by using the file directly, it's probably enough in term of performance as it's not for any lists and only quering like 40 keys on specific user actions.

**Comment by ammarahm-ed** [comment]
@HugoGresse  Ok so after testing on real device and emulator:

```js
  const prefix = 'mmkvkeyData';
  const exampleData = 'abcdefghijklmnopqrstuvwxyz';

        let max = 1000;
        let now = performance.now();

        for (var i = 0; i < max; i++) {
            storage.setString(prefix + i, exampleData); 
        }
        console.log(performance.now() - now);
```
It's better to use `performance.now` since it's more accurate so test with that.

On a real device & emulator writing 1000 keys takes around 1.5 seconds on first write and then 0.5 on real device and around 1s on emulator.

Real Device: LG G7 Snapdragon 840, 4GB Ram
Emulator: i5 4th gen 8GB ram.

Can you give me an average value size? or one of the values for a key in your file. How big it is so I can do more precise tests.
Also what is the difference in time taken on first write & 2nd write of the same data. So writing 1000 keys once and then write them again. I have seen that writing for the first time takes more time, maybe because the actual file needs to be resized as 64->128->256->512 and so on, taking more time than actual writing data.

**Comment by HugoGresse** [comment]
@ammarahm-ed thanks for your help here. 
Based on my usage of mmkv, I've decided to not use it. I don't need to write to the db and will use files to read them directly. 
I've switched the file to flatbuffers to improve read speed and it's perfect for this use case. 
Keep on your good work on mmkv-storage (maybe merge it with react-native-mmkv?), I'm not sure if there is room to have two libs doing the exacte same work on RN.
