### ISSUE TITLE
[Security Question] - Security question regrading encryption 

### ISSUE THREAD

**Issue by KJ-GM** [ammarahm-ed/react-native-mmkv-storage#206]
**Question 1**

Hello, we are currently working on a password manager app, I would like to ask as if the encryption provided by this library is reliable for storing a **`Secret key`**  and **`Sensitive`** data for local usage?

**Question 2**

I know that data is **`persistent`**  when app installed and in usage, what happens if user **`uninstall`** the app, dose the storage gets deleted ? if not, how can it be deleted?

**Comment by ammarahm-ed** [comment]
> Question 1

MMKV uses `AES CFB-128` for encryption of your data. This library manages encryption for you by using Platform Keychain on iOS and Android. All you have to do is call 1 function and everything else is handled automatically from creating and storing encryption keys in Keychain to decrypting data on app launch. The encryption used is reliable enough for storing sensitive data. 

> Question 2

Once you uninstall the app, the data is automatically deleted from the phone since it is stored in App's data/ directory.

**Comment by KJ-GM** [comment]
> > Question 1
> 
> MMKV uses `AES CFB-128` for encryption of your data. This library manages encryption for you by using Platform Keychain on iOS and Android. All you have to do is call 1 function and everything else is handled automatically from creating and storing encryption keys in Keychain to decrypting data on app launch. The encryption used is reliable enough for storing sensitive data.
> 
> > Question 2
> 
> Once you uninstall the app, the data is automatically deleted from the phone since it is stored in App's data/ directory.

Thank you for information, One more question:

-  I can see that there are `async` and `sync` functions for getting storage values, not sure when to use what ?

For example, I have to get if user has lunched the app for first time,

Shall I use it with async when app first starts:

`MMKV.getBoolAsync(isFirstLunch)`

Or 

Is it enough with sync method to check straight in the navigation

`MMKV.getBool(isFirstLunch)`

**what makes a difference?**

**Comment by ammarahm-ed** [comment]
@KJA-Tsx Async and Sync functions exist for backward compatibility with older versions of this library. If you want more performance, use Sync functions. In the above case for example, use `MMKV.getBool(isFirstLunch)`

**Comment by KJ-GM** [comment]
Thank you for support.
