### ISSUE TITLE
Version 0.3.5 can't get encrypted data, but version 0.3.2 can

### ISSUE THREAD

**Issue by pnthach95** [ammarahm-ed/react-native-mmkv-storage#30]
Reproduce on Android, untest on iOS:

- Clone [my example](https://github.com/pnthach95/mmkvtest), make sure `react-native-mmkv-storage` version is 0.3.5
- Run project
- Enter username and password, check Save data
- Press Log in
- If you see `Login success`, kill app
- Open app and expect username and password in `TextInput`s but no
- Install version 0.3.2 and run project => Username and password show up

**Comment by ammarahm-ed** [comment]
Hey I fixed the issue in the latest release. Thank you for reporting.

**Comment by LeDevFou** [comment]
First of all thank you for this package.

Still impossible to read data encrypted with version 0.3.7 or 0.3.5 (work with 0.3.2).

It works only (with version 0.3.7) if I downgrade mmkv-static version to 1.1.2 (instead of 1.2.2)

**Comment by ammarahm-ed** [comment]
@LeDevFou Maybe it got broken again, I had fixed it in v0.3.6 I will see what is happening. Its only not working on android or ios too?

**Comment by LeDevFou** [comment]
@ammarahm-ed  Thank you.

Sorry I can't test with IOS.
I tested on a real Android device and it gives the same result.

This seems to come from an error with the 1.2.X version of mmkv.  Whatever the version (0.3.2 ... 0.3.7) it works with version 1.1.X but none of them works with 1.2.X.

**Comment by LeDevFou** [comment]
@ammarahm-ed 

After some testing I noticed that the problem comes from with the boolean values only.

The problem seems come from MMKV which does not store correctly boolean.
[https://github.com/Tencent/MMKV/issues/529](https://github.com/Tencent/MMKV/issues/529)



During my tests I noticed a small problem in the file "IDStore.java".


```
        HashMap<String, Object> child = new HashMap<>();
        child.put("ID", ID);
        child.put("encrypted", encrypted);
-       child.put(alias, alias); // <= quotes are missing
+       child.put("alias", alias);  
        IdStore.put(ID, child);
```

**Comment by ammarahm-ed** [comment]
@LeDevFou Seems like it has been fixed in the dev branch and nice catch! i just fixed the alias problem, you were right. alias value was passed as the key, that can be another reason for being unable to find the encrypted storage.

I will wait until the new version of MMKV comes our and update the library!
