### ISSUE TITLE
CMake Deprecation Warning:The 'cmake-server(7)' is deprecated. Please port clients to use the 'cmake-file-api(7)' instead.

### ISSUE THREAD

**Issue by flixyudh** [ammarahm-ed/react-native-mmkv-storage#73]
Hi, I have a problem to install R-N-MMKV-S in my project
when I use `react-native run-android` I got this error

<img width="828" alt="Screen Shot 2021-03-18 at 10 08 13" src="https://user-images.githubusercontent.com/19633881/111567631-dbc57e80-87d1-11eb-9a35-bbc88f32bef3.png">

I didn't installed android studio because of storage issue, but I'm able to setup `NDK` and `CMake` using `standalone SDK Manager` (without android studio sdk manager)

I've found this [issue](https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/62), but the suggestion didn't solve my problem

Version Info:
React Native : 0.63.4
CMake : 3.19.7
NDK : 22.0.7026061 (not remember)

**Comment by ammarahm-ed** [comment]
The problem is not related to this library but how you have setup your build system which isnt the usual case. maybe this question stack overflow can help: https://stackoverflow.com/questions/38658014/ninja-not-found-by-cmake 

also this: https://stackoverflow.com/questions/54666491/ndk-build-error-for-ninja-cmake-make-program-is-not-set

setup `cmake.dir`& `ndk.dir` in local.properties manually.
